apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/NGC-337-2/eventyx-gitops-manifests.git
    targetRevision: main
    path: apps/myapp       # 👈 Path to the Chart.yaml directory
    helm:                  # 👈 Tell ArgoCD this is a Helm chart
      valueFiles:
        - values.yaml
      parameters:
        - name: replicaCount
          value: "2"       # 👈 Override values directly here if needed
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp       # 👈 Target namespace
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true # 👈 Auto-create 'myapp' namespace